//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Chat.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Demo;

public interface ChatServer extends com.zeroc.Ice.Object
{
    void register(String username, ChatClientPrx client, com.zeroc.Ice.Current current);

    void initiateCall(String fromUser, String toUser, com.zeroc.Ice.Current current);

    void answerCall(String fromUser, String toUser, com.zeroc.Ice.Current current);

    void rejectCall(String fromUser, String toUser, com.zeroc.Ice.Current current);

    void sendAudio(String fromUser, String toUser, byte[] data, com.zeroc.Ice.Current current);

    void initiateGroupCall(String fromUser, String groupName, com.zeroc.Ice.Current current);

    void answerGroupCall(String fromUser, String groupName, com.zeroc.Ice.Current current);

    void sendGroupAudio(String fromUser, String groupName, byte[] data, com.zeroc.Ice.Current current);

    /** @hidden */
    static final String[] _iceIds =
    {
        "::Demo::ChatServer",
        "::Ice::Object"
    };

    @Override
    default String[] ice_ids(com.zeroc.Ice.Current current)
    {
        return _iceIds;
    }

    @Override
    default String ice_id(com.zeroc.Ice.Current current)
    {
        return ice_staticId();
    }

    static String ice_staticId()
    {
        return "::Demo::ChatServer";
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_register(ChatServer obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_username;
        ChatClientPrx iceP_client;
        iceP_username = istr.readString();
        iceP_client = ChatClientPrx.uncheckedCast(istr.readProxy());
        inS.endReadParams();
        obj.register(iceP_username, iceP_client, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_initiateCall(ChatServer obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_fromUser;
        String iceP_toUser;
        iceP_fromUser = istr.readString();
        iceP_toUser = istr.readString();
        inS.endReadParams();
        obj.initiateCall(iceP_fromUser, iceP_toUser, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_answerCall(ChatServer obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_fromUser;
        String iceP_toUser;
        iceP_fromUser = istr.readString();
        iceP_toUser = istr.readString();
        inS.endReadParams();
        obj.answerCall(iceP_fromUser, iceP_toUser, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_rejectCall(ChatServer obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_fromUser;
        String iceP_toUser;
        iceP_fromUser = istr.readString();
        iceP_toUser = istr.readString();
        inS.endReadParams();
        obj.rejectCall(iceP_fromUser, iceP_toUser, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_sendAudio(ChatServer obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_fromUser;
        String iceP_toUser;
        byte[] iceP_data;
        iceP_fromUser = istr.readString();
        iceP_toUser = istr.readString();
        iceP_data = istr.readByteSeq();
        inS.endReadParams();
        obj.sendAudio(iceP_fromUser, iceP_toUser, iceP_data, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_initiateGroupCall(ChatServer obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_fromUser;
        String iceP_groupName;
        iceP_fromUser = istr.readString();
        iceP_groupName = istr.readString();
        inS.endReadParams();
        obj.initiateGroupCall(iceP_fromUser, iceP_groupName, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_answerGroupCall(ChatServer obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_fromUser;
        String iceP_groupName;
        iceP_fromUser = istr.readString();
        iceP_groupName = istr.readString();
        inS.endReadParams();
        obj.answerGroupCall(iceP_fromUser, iceP_groupName, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_sendGroupAudio(ChatServer obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_fromUser;
        String iceP_groupName;
        byte[] iceP_data;
        iceP_fromUser = istr.readString();
        iceP_groupName = istr.readString();
        iceP_data = istr.readByteSeq();
        inS.endReadParams();
        obj.sendGroupAudio(iceP_fromUser, iceP_groupName, iceP_data, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /** @hidden */
    final static String[] _iceOps =
    {
        "answerCall",
        "answerGroupCall",
        "ice_id",
        "ice_ids",
        "ice_isA",
        "ice_ping",
        "initiateCall",
        "initiateGroupCall",
        "register",
        "rejectCall",
        "sendAudio",
        "sendGroupAudio"
    };

    /** @hidden */
    @Override
    default java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceDispatch(com.zeroc.IceInternal.Incoming in, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        int pos = java.util.Arrays.binarySearch(_iceOps, current.operation);
        if(pos < 0)
        {
            throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
        }

        switch(pos)
        {
            case 0:
            {
                return _iceD_answerCall(this, in, current);
            }
            case 1:
            {
                return _iceD_answerGroupCall(this, in, current);
            }
            case 2:
            {
                return com.zeroc.Ice.Object._iceD_ice_id(this, in, current);
            }
            case 3:
            {
                return com.zeroc.Ice.Object._iceD_ice_ids(this, in, current);
            }
            case 4:
            {
                return com.zeroc.Ice.Object._iceD_ice_isA(this, in, current);
            }
            case 5:
            {
                return com.zeroc.Ice.Object._iceD_ice_ping(this, in, current);
            }
            case 6:
            {
                return _iceD_initiateCall(this, in, current);
            }
            case 7:
            {
                return _iceD_initiateGroupCall(this, in, current);
            }
            case 8:
            {
                return _iceD_register(this, in, current);
            }
            case 9:
            {
                return _iceD_rejectCall(this, in, current);
            }
            case 10:
            {
                return _iceD_sendAudio(this, in, current);
            }
            case 11:
            {
                return _iceD_sendGroupAudio(this, in, current);
            }
        }

        assert(false);
        throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
    }
}
