//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Chat.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

/* eslint-disable */
/* jshint ignore: start */

(function(module, require, exports)
{
    const Ice = require("ice").Ice;
    const _ModuleRegistry = Ice._ModuleRegistry;
    const Slice = Ice.Slice;

    let Demo = _ModuleRegistry.module("Demo");

    Slice.defineSequence(Demo, "AudioDataHelper", "Ice.ByteHelper", true);

    const iceC_Demo_ChatClient_ids = [
        "::Demo::ChatClient",
        "::Ice::Object"
    ];

    Demo.ChatClient = class extends Ice.Object
    {
    };

    Demo.ChatClientPrx = class extends Ice.ObjectPrx
    {
    };

    Slice.defineOperations(Demo.ChatClient, Demo.ChatClientPrx, iceC_Demo_ChatClient_ids, 0,
    {
        "incomingCall": [, , , , , [[7]], , , , ],
        "callAccepted": [, , , , , [[7]], , , , ],
        "callRejected": [, , , , , [[7]], , , , ],
        "receiveAudio": [, , , , , [["Demo.AudioDataHelper"]], , , , ],
        "receiveVoiceNote": [, , , , , [[7], ["Demo.AudioDataHelper"]], , , , ]
    });

    const iceC_Demo_ChatServer_ids = [
        "::Demo::ChatServer",
        "::Ice::Object"
    ];

    Demo.ChatServer = class extends Ice.Object
    {
    };

    Demo.ChatServerPrx = class extends Ice.ObjectPrx
    {
    };

    Slice.defineOperations(Demo.ChatServer, Demo.ChatServerPrx, iceC_Demo_ChatServer_ids, 0,
    {
        "register": [, , , , , [[7], ["Demo.ChatClientPrx"]], , , , ],
        "initiateCall": [, , , , , [[7], [7]], , , , ],
        "answerCall": [, , , , , [[7], [7]], , , , ],
        "rejectCall": [, , , , , [[7], [7]], , , , ],
        "sendAudio": [, , , , , [[7], [7], ["Demo.AudioDataHelper"]], , , , ],
        "sendVoiceNote": [, , , , , [[7], [7], ["Demo.AudioDataHelper"]], , , , ]
    });
    exports.Demo = Demo;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require :
 (typeof WorkerGlobalScope !== "undefined" && self instanceof WorkerGlobalScope) ? self.Ice._require : window.Ice._require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports :
 (typeof WorkerGlobalScope !== "undefined" && self instanceof WorkerGlobalScope) ? self : window));
